<?php //$Id$

/**
 * @file
 * Replaces the default HTML 'Add to Cart' button with a more attractive graphic.
 * 
 * See http://www.primalmedia.com/blog/replace-add-cart-button-image-ubercart
 */

/**
 * Implementation of hook_form_alter().
 */
function uc_gfxbtn_form_alter($form_id, &$form) {
if(( $form_id['#validate'][0] == 'uc_product_add_to_cart_form_validate' && $form_id['#submit'][0] == 'uc_product_add_to_cart_form_submit') OR ( $form_id['#validate'][0] == 'uc_catalog_buy_it_now_form_validate' && $form_id['#submit'][0] == 'uc_catalog_buy_it_now_form_submit') OR ( $form_id['#validate'][0] == 'uc_product_buy_it_now_form_validate' && $form_id['#submit'][0] == 'uc_product_buy_it_now_form_submit')){

$form_id['submit']['#type'] = 'hidden';

// strip '?submit_x=15&submit_y=27' from $_POST
if (isset($_POST['submit_x'])) {
$form_id['submit'] = array(  
'#type' => 'submit',
'#value' => 'submit',
);
}

$form_id['submit_image'] = array(
'#value' => '<input name="submit" type="image" width="147" height="29" class="add_to_cart" title="'. t('Add to Shopping Cart') .'" src="/'. drupal_get_path('module', 'uc_gfxbtn') .
'/Buttons_purchase.png">',
);
}
}

