<?php

include_once('udi_features_news_central.features.inc');

define('JURISDICTION_CLAUSE', 2);
define('ISSUE_CLAUSE', 3);

define('SINGLE_JURISDICTION_ARG', 1);
define('SINGLE_ISSUE_ARG', 2);

define('MULTI_JURISDICTION_ARG', 2);
define('MULTI_ISSUE_ARG', 3);

/**
 * Implementation of hook_views_query_alter()
 *
 */
function udi_features_news_central_views_query_alter(&$view, &$query) {
  if ($view->name == 'udi_news_central' || $view->name == 'udi_news_central_media_releases' || $view->name == 'udi_news_central_news') {  
    unset($query->table_queue['term_node_value_0']['join']->extra);
    unset($query->table_queue['term_node_value_1']['join']->extra);

    // Jurisdiction filter
    // NOTE: this filter occupies element 1 in args and element 2 clauses
    if (isset($_GET['j'])) {
      if ($view->name == 'udi_news_central') {
        $query->where[0]['args'][MULTI_JURISDICTION_ARG] = $_GET['j'];
      }
      else {
        $query->where[0]['args'][SINGLE_JURISDICTION_ARG] = $_GET['j'];
      }
    }
    else {
      unset($query->where[0]['clauses'][JURISDICTION_CLAUSE]);      
      if ($view->name == 'udi_news_central') {
        unset($query->where[0]['args'][MULTI_JURISDICTION_ARG]);
      }
      else {
        unset($query->where[0]['args'][SINGLE_JURISDICTION_ARG]);
      }
    }

    // Issue filter
    // NOTE: this filter occupies element 2 in args and element 3 clauses
    if (isset($_GET['i'])) {
      if ($view->name == 'udi_news_central') {
        $query->where[0]['args'][MULTI_ISSUE_ARG] = $_GET['i'];
      }
      else {
        $query->where[0]['args'][SINGLE_ISSUE_ARG] = $_GET['i'];
      }
    }
    else {
      unset($query->where[0]['clauses'][ISSUE_CLAUSE]);
      if ($view->name == 'udi_news_central') {
        unset($query->where[0]['args'][MULTI_ISSUE_ARG]);
      }
      else {
        unset($query->where[0]['args'][SINGLE_ISSUE_ARG]);
      }
    }
    
    // Year filter
    // NOTE: this filter always occupies the date element of the query
    if (isset($_GET['y'])) {
      $clause = sprintf("YEAR(node_data_field_news_date.field_news_date_value) = %d", (int)$_GET['y']);
      $query->where['date']['clauses'][0] = $clause;
    }
    else {
      unset($query->where['date']);
    }
  }
}

/**
 * Implementation of hook_block()
 *
 */
function udi_features_news_central_block($op = 'list', $delta = 0, $edit = array()) {
  switch ($op) {
    case 'list':
      $blocks['news-central-filter'] = array(
        'info' => t("UDI News Central Filter Block"),
        'weight' => 0,
        'cache' => BLOCK_NO_CACHE
      );
      
      return $blocks;
    break;
    
    case 'view':
      $block = array();
      
      if ($delta == 'news-central-filter') {
        $block['subject'] = t('UDI News Central Filter');
        
        // The content-type that the block support is tightly couple to the
        // URL of the View. Currently only 'news' and 'media-releases' are supported.
        // PATH[0] must be 'news-central'
        // PATH[1] must be 'news' or 'media-releases'
        $path = explode('/', $_GET['q']);
        if ($path[0] == 'news-central' && $path[1] == 'news') {
          $block['content'] = drupal_get_form('udi_features_news_central_block_filter_form', true, false);
        }
        else if ($path[0] == 'news-central' && $path[1] == 'media-releases') {
          $block['content'] = drupal_get_form('udi_features_news_central_block_filter_form', false, true);
        }
        else if ($path[0] == 'news-central') {
          $block['content'] = drupal_get_form('udi_features_news_central_block_filter_form', true, true);
        }
      }
      
      return $block;
    break;
  }
}

function udi_features_news_central_block_filter_form(&$form_state, $news, $media) {
  $qs = $_GET;
  unset($qs['q']);
  
  $jurisdictions = array();
  $issues = array();
  $years = array();
 
  // Jurisdiction and Issue taxonomies
  $sql = "SELECT v.vid FROM {vocabulary} v WHERE LOWER(v.name) LIKE LOWER('%s')";
  $jvid = db_result(db_query($sql, 'Jurisdiction'));
  $ivid = db_result(db_query($sql, 'Issue'));
  
  $sql = "SELECT t.name, t.tid FROM {term_data} t WHERE t.vid = %d ORDER BY t.weight, t.name ASC";
  $result = db_query($sql, $jvid);
  while ($row = db_fetch_object($result)) {
    $jurisdictions[$row->tid] = $row->name;
  }

  $result = db_query($sql, $ivid);
  while ($row = db_fetch_object($result)) {
    $issues[$row->tid] = $row->name;
  }
  
  // Year values
  $sql = "
    SELECT MIN(YEAR(nd.field_news_date_value)) AS min, MAX(YEAR(nd.field_news_date_value)) AS max 
    FROM {node} n
      INNER JOIN {content_field_news_date} nd ON nd.nid = n.nid AND nd.vid = n.vid
  ";
  if ($news && !$media) {
    $sql .= sprintf(" WHERE n.type = '%s' AND n.status = %d", 'news_item', 1);
  }
  else if (!$news && $media) {
    $sql .= sprintf(" WHERE n.type = '%s' AND n.status = %d", 'press_release', 1);
  }
  else {
    $sql .= sprintf(" WHERE (n.type = '%s' OR n.type = '%s') AND n.status = %d", 'news_item', 'press_release', 1);
  }
  
  if ($result = db_fetch_object(db_query($sql))) {
    for ($i = (int)$result->max; $i >= (int)$result->min; $i--) {
      $years[$i] = $i;
    }
  }
  
  $form['jurisdiction'] = array(
    '#type' => 'select',
    '#title' => t('Jurisdiction'),
    '#options' => !empty($jurisdictions) ? array('all' => t('All')) + $jurisdictions : array('all' => t('All')),
    '#default_value' => $qs['j']
  );
  
  $form['issue'] = array(
    '#type' => 'select',
    '#title' => t('Issue'),
    '#options' => !empty($issues) ? array('all' => t('All')) + $issues : array('all' => t('All')),
    '#default_value' => $qs['i']
  );
  
  $form['year'] = array(
    '#type' => 'select',
    '#title' => t('Year'),
    '#options' => !empty($years) ? array('all' => t('All')) + $years : array('all' => t('All')),
    '#default_value' => $qs['y']
  );
  
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Go')
  );

  return $form;
}

function udi_features_news_central_block_filter_form_submit($form, &$form_state) {
  $qs = array();
  
  if ($form_state['values']['year'] != 'all') {
    $qs['y'] = (int)$form_state['values']['year'];
  }  
  
  if ($form_state['values']['jurisdiction'] != 'all') {
    $qs['j'] = (int)$form_state['values']['jurisdiction'];
  }
  
  if ($form_state['values']['issue'] != 'all') {
    $qs['i'] = (int)$form_state['values']['issue'];
  }

  if (!empty($qs)) {
    drupal_goto($_GET['q'], $qs);
  }
}
